import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GlobalFAB } from "../components/FAB/GlobalFAB";
import { FABProvider } from "../components/FAB/FABContext";
import { ConflictResolutionManager } from "../components/ConflictResolution";
import { JotaiProvider } from "../lib/JotaiProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <JotaiProvider>
          <FABProvider>
            {children}
            <GlobalFAB />
            <ConflictResolutionManager />
          </FABProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
